version: 2
updates:
- package-ecosystem: nuget
  directory: "/src"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.Extensions.DependencyInjection.Specification.Tests
    versions:
    - 3.1.11
    - 3.1.12
    - 3.1.13
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
    - 16.9.1
  - dependency-name: coverlet.collector
    versions:
    - 3.0.2
